### ISSUE TITLE
Failed to create airtable

### ISSUE THREAD

**Issue by mecaz** [tinkerthon/volumio-rfid#3]
Hello, 

I have bought rc522 and installed successfully it works with testfiles.
when play.py in your project. it gives me following error.

"~/volumio-rfid$ sudo python3 play.py
Warte auf Karte
Karte 432809675103
Traceback (most recent call last):
  File "play.py", line 119, in <module>
    play(id)
  File "play.py", line 51, in play
    uri = search(id)
  File "play.py", line 42, in search
    headers = { 'Authorization': 'Bearer ' + env['Airtable']['apikey'] }
  File "/usr/lib/python3.4/configparser.py", line 937, in __getitem__
    raise KeyError(key)"  

i signup an airtable account. copied api key in .env file that locaded in /volumio-rfid folder. 
created a file in airtable like that https://pasteboard.co/J7U8Whj.jpg 
but i couldnt make it run anyway. 
Regards

**Comment by mecaz** [comment]
Hello again, 

I renamed volumio-rfid folder to rfid and run "sudo python play.py" and got following error.

{"error":{"type":"INVALID_PERMISSIONS","message":"Invalid permissions"}}

please help. thanks
